//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcSyncDeltaRCAMSCombRuleDtlField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcSyncDeltaRCAMSCombRuleDtlField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcSyncDeltaRCAMSCombRuleDtlField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcSyncDeltaRCAMSCombRuleDtlField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthosttradeapiPINVOKE.delete_CThostFtdcSyncDeltaRCAMSCombRuleDtlField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string TradingDay {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_TradingDay_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_TradingDay_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string ProdGroup {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ProdGroup_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ProdGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string RuleId {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_RuleId_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_RuleId_get(swigCPtr);
      return ret;
    } 
  }

  public int Priority {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_Priority_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_Priority_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double CombMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_CombMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_CombMargin_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeInstID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ExchangeInstID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ExchangeInstID_get(swigCPtr);
      return ret;
    } 
  }

  public int LegID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_LegID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_LegID_get(swigCPtr);
      return ret;
    } 
  }

  public string LegInstrumentID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_LegInstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_LegInstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public char Direction {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_Direction_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_Direction_get(swigCPtr);
      return ret;
    } 
  }

  public int LegMultiple {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_LegMultiple_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_LegMultiple_get(swigCPtr);
      return ret;
    } 
  }

  public char ActionDirection {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ActionDirection_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_ActionDirection_get(swigCPtr);
      return ret;
    } 
  }

  public int SyncDeltaSequenceNo {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_SyncDeltaSequenceNo_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaRCAMSCombRuleDtlField_SyncDeltaSequenceNo_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcSyncDeltaRCAMSCombRuleDtlField() : this(ctpthosttradeapiPINVOKE.new_CThostFtdcSyncDeltaRCAMSCombRuleDtlField(), true) {
  }

}
