//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcRCAMSInvestorCombPositionField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcRCAMSInvestorCombPositionField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcRCAMSInvestorCombPositionField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcRCAMSInvestorCombPositionField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthosttradeapiPINVOKE.delete_CThostFtdcRCAMSInvestorCombPositionField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string ExchangeID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string BrokerID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char PosiDirection {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_PosiDirection_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_PosiDirection_get(swigCPtr);
      return ret;
    } 
  }

  public string CombInstrumentID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_CombInstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_CombInstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public int LegID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_LegID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_LegID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeInstID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_ExchangeInstID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_ExchangeInstID_get(swigCPtr);
      return ret;
    } 
  }

  public int TotalAmt {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_TotalAmt_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_TotalAmt_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_ExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_ExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double Margin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_Margin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRCAMSInvestorCombPositionField_Margin_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcRCAMSInvestorCombPositionField() : this(ctpthosttradeapiPINVOKE.new_CThostFtdcRCAMSInvestorCombPositionField(), true) {
  }

}
