//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcTransferHeaderField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcTransferHeaderField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcTransferHeaderField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcTransferHeaderField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthosttradeapiPINVOKE.delete_CThostFtdcTransferHeaderField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string Version {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_Version_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_Version_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeCode {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeCode_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeCode_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeDate {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeDate_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeDate_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeTime {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeTime_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeTime_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeSerial {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeSerial_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_TradeSerial_get(swigCPtr);
      return ret;
    } 
  }

  public string FutureID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_FutureID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_FutureID_get(swigCPtr);
      return ret;
    } 
  }

  public string BankID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_BankID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_BankID_get(swigCPtr);
      return ret;
    } 
  }

  public string BankBrchID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_BankBrchID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_BankBrchID_get(swigCPtr);
      return ret;
    } 
  }

  public string OperNo {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_OperNo_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_OperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string DeviceID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_DeviceID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_DeviceID_get(swigCPtr);
      return ret;
    } 
  }

  public string RecordNum {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_RecordNum_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_RecordNum_get(swigCPtr);
      return ret;
    } 
  }

  public int SessionID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_SessionID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_SessionID_get(swigCPtr);
      return ret;
    } 
  }

  public int RequestID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_RequestID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcTransferHeaderField_RequestID_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcTransferHeaderField() : this(ctpthosttradeapiPINVOKE.new_CThostFtdcTransferHeaderField(), true) {
  }

}
