//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcRULEInstrParameterField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcRULEInstrParameterField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcRULEInstrParameterField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcRULEInstrParameterField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthosttradeapiPINVOKE.delete_CThostFtdcRULEInstrParameterField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string TradingDay {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_TradingDay_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_TradingDay_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public char InstrumentClass {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_InstrumentClass_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_InstrumentClass_get(swigCPtr);
      return ret;
    } 
  }

  public string StdInstrumentID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_StdInstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_StdInstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public double BSpecRatio {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_BSpecRatio_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_BSpecRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double SSpecRatio {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_SSpecRatio_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_SSpecRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double BHedgeRatio {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_BHedgeRatio_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_BHedgeRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double SHedgeRatio {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_SHedgeRatio_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_SHedgeRatio_get(swigCPtr);
      return ret;
    } 
  }

  public double BAddOnMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_BAddOnMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_BAddOnMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SAddOnMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_SAddOnMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_SAddOnMargin_get(swigCPtr);
      return ret;
    } 
  }

  public int CommodityGroupID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_CommodityGroupID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcRULEInstrParameterField_CommodityGroupID_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcRULEInstrParameterField() : this(ctpthosttradeapiPINVOKE.new_CThostFtdcRULEInstrParameterField(), true) {
  }

}
