//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcInvestorProdSPBMDetailField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcInvestorProdSPBMDetailField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcInvestorProdSPBMDetailField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcInvestorProdSPBMDetailField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthosttradeapiPINVOKE.delete_CThostFtdcInvestorProdSPBMDetailField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string ExchangeID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string BrokerID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string ProdFamilyCode {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_ProdFamilyCode_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_ProdFamilyCode_get(swigCPtr);
      return ret;
    } 
  }

  public double IntraInstrMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_IntraInstrMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_IntraInstrMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double BCollectingMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_BCollectingMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_BCollectingMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SCollectingMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_SCollectingMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_SCollectingMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double IntraProdMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_IntraProdMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_IntraProdMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double NetMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_NetMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_NetMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double InterProdMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_InterProdMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_InterProdMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SingleMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_SingleMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_SingleMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AddOnMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_AddOnMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_AddOnMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double DeliveryMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_DeliveryMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_DeliveryMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double CallOptionMinRisk {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_CallOptionMinRisk_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_CallOptionMinRisk_get(swigCPtr);
      return ret;
    } 
  }

  public double PutOptionMinRisk {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_PutOptionMinRisk_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_PutOptionMinRisk_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionMinRisk {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_OptionMinRisk_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_OptionMinRisk_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionValueOffset {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_OptionValueOffset_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_OptionValueOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionRoyalty {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_OptionRoyalty_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_OptionRoyalty_get(swigCPtr);
      return ret;
    } 
  }

  public double RealOptionValueOffset {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_RealOptionValueOffset_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_RealOptionValueOffset_get(swigCPtr);
      return ret;
    } 
  }

  public double Margin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_Margin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_Margin_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_ExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcInvestorProdSPBMDetailField_ExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcInvestorProdSPBMDetailField() : this(ctpthosttradeapiPINVOKE.new_CThostFtdcInvestorProdSPBMDetailField(), true) {
  }

}
