//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcSyncDeltaInitInvstMarginField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcSyncDeltaInitInvstMarginField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcSyncDeltaInitInvstMarginField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcSyncDeltaInitInvstMarginField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthosttradeapiPINVOKE.delete_CThostFtdcSyncDeltaInitInvstMarginField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public double LastRiskTotalInvstMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskTotalInvstMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskTotalInvstMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LastRiskTotalExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskTotalExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskTotalExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ThisSyncInvstMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncInvstMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncInvstMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ThisSyncExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double RemainRiskInvstMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskInvstMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskInvstMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double RemainRiskExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LastRiskSpecTotalInvstMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskSpecTotalInvstMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskSpecTotalInvstMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LastRiskSpecTotalExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskSpecTotalExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_LastRiskSpecTotalExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ThisSyncSpecInvstMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncSpecInvstMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncSpecInvstMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ThisSyncSpecExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncSpecExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_ThisSyncSpecExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double RemainRiskSpecInvstMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskSpecInvstMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskSpecInvstMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double RemainRiskSpecExchMargin {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskSpecExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_RemainRiskSpecExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public int SyncDeltaSequenceNo {
    set {
      ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_SyncDeltaSequenceNo_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthosttradeapiPINVOKE.CThostFtdcSyncDeltaInitInvstMarginField_SyncDeltaSequenceNo_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcSyncDeltaInitInvstMarginField() : this(ctpthosttradeapiPINVOKE.new_CThostFtdcSyncDeltaInitInvstMarginField(), true) {
  }

}
