//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcSyncDelaySwapField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcSyncDelaySwapField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcSyncDelaySwapField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcSyncDelaySwapField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          thostmdapiPINVOKE.delete_CThostFtdcSyncDelaySwapField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string DelaySwapSeqNo {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_DelaySwapSeqNo_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_DelaySwapSeqNo_get(swigCPtr);
      return ret;
    } 
  }

  public string BrokerID {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string FromCurrencyID {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromCurrencyID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromCurrencyID_get(swigCPtr);
      return ret;
    } 
  }

  public double FromAmount {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromAmount_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double FromFrozenSwap {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromFrozenSwap_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromFrozenSwap_get(swigCPtr);
      return ret;
    } 
  }

  public double FromRemainSwap {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromRemainSwap_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_FromRemainSwap_get(swigCPtr);
      return ret;
    } 
  }

  public string ToCurrencyID {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_ToCurrencyID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_ToCurrencyID_get(swigCPtr);
      return ret;
    } 
  }

  public double ToAmount {
    set {
      thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_ToAmount_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcSyncDelaySwapField_ToAmount_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcSyncDelaySwapField() : this(thostmdapiPINVOKE.new_CThostFtdcSyncDelaySwapField(), true) {
  }

}
