//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcSuperUserField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcSuperUserField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcSuperUserField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcSuperUserField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcSuperUserField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string UserID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_UserID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_UserID_get(swigCPtr);
      return ret;
    } 
  }

  public string UserName {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_UserName_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_UserName_get(swigCPtr);
      return ret;
    } 
  }

  public string Password {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_Password_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_Password_get(swigCPtr);
      return ret;
    } 
  }

  public int IsActive {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_IsActive_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcSuperUserField_IsActive_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcSuperUserField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcSuperUserField(), true) {
  }

}
