//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcBrokerUserEventField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcBrokerUserEventField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcBrokerUserEventField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcBrokerUserEventField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcBrokerUserEventField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string UserID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_UserID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_UserID_get(swigCPtr);
      return ret;
    } 
  }

  public char UserEventType {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_UserEventType_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_UserEventType_get(swigCPtr);
      return ret;
    } 
  }

  public int EventSequenceNo {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_EventSequenceNo_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_EventSequenceNo_get(swigCPtr);
      return ret;
    } 
  }

  public string EventDate {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_EventDate_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_EventDate_get(swigCPtr);
      return ret;
    } 
  }

  public string EventTime {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_EventTime_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_EventTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UserEventInfo {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_UserEventInfo_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_UserEventInfo_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_reserve1_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_reserve1_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcBrokerUserEventField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcBrokerUserEventField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcBrokerUserEventField(), true) {
  }

}
