//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcAuthenticationInfoField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcAuthenticationInfoField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcAuthenticationInfoField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcAuthenticationInfoField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcAuthenticationInfoField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string UserID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_UserID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_UserID_get(swigCPtr);
      return ret;
    } 
  }

  public string UserProductInfo {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_UserProductInfo_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_UserProductInfo_get(swigCPtr);
      return ret;
    } 
  }

  public string AuthInfo {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_AuthInfo_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_AuthInfo_get(swigCPtr);
      return ret;
    } 
  }

  public int IsResult {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_IsResult_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_IsResult_get(swigCPtr);
      return ret;
    } 
  }

  public string AppID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_AppID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_AppID_get(swigCPtr);
      return ret;
    } 
  }

  public char AppType {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_AppType_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_AppType_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_reserve1_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_reserve1_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientIPAddress {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_ClientIPAddress_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcAuthenticationInfoField_ClientIPAddress_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcAuthenticationInfoField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcAuthenticationInfoField(), true) {
  }

}
