//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcQryClassifiedInstrumentField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcQryClassifiedInstrumentField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcQryClassifiedInstrumentField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcQryClassifiedInstrumentField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcQryClassifiedInstrumentField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string InstrumentID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeInstID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ExchangeInstID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ExchangeInstID_get(swigCPtr);
      return ret;
    } 
  }

  public string ProductID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ProductID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ProductID_get(swigCPtr);
      return ret;
    } 
  }

  public char TradingType {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_TradingType_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_TradingType_get(swigCPtr);
      return ret;
    } 
  }

  public char ClassType {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ClassType_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcQryClassifiedInstrumentField_ClassType_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcQryClassifiedInstrumentField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcQryClassifiedInstrumentField(), true) {
  }

}
