//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcOptionInstrTradeCostField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcOptionInstrTradeCostField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcOptionInstrTradeCostField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcOptionInstrTradeCostField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          thostmdapiPINVOKE.delete_CThostFtdcOptionInstrTradeCostField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double FixedMargin {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_FixedMargin_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_FixedMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double MiniMargin {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_MiniMargin_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_MiniMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double Royalty {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_Royalty_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_Royalty_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchFixedMargin {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_ExchFixedMargin_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_ExchFixedMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchMiniMargin {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_ExchMiniMargin_set(swigCPtr, value);
    } 
    get {
      double ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_ExchMiniMargin_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestUnitID {
    set {
      thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_InvestUnitID_set(swigCPtr, value);
    } 
    get {
      string ret = thostmdapiPINVOKE.CThostFtdcOptionInstrTradeCostField_InvestUnitID_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcOptionInstrTradeCostField() : this(thostmdapiPINVOKE.new_CThostFtdcOptionInstrTradeCostField(), true) {
  }

}
