//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcOptionSelfCloseField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcOptionSelfCloseField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcOptionSelfCloseField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcOptionSelfCloseField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcOptionSelfCloseField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_reserve1_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_reserve1_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionSelfCloseRef {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptionSelfCloseRef_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptionSelfCloseRef_get(swigCPtr);
      return ret;
    } 
  }

  public string UserID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_UserID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_UserID_get(swigCPtr);
      return ret;
    } 
  }

  public int Volume {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_Volume_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_Volume_get(swigCPtr);
      return ret;
    } 
  }

  public int RequestID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_RequestID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_RequestID_get(swigCPtr);
      return ret;
    } 
  }

  public string BusinessUnit {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BusinessUnit_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BusinessUnit_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OptSelfCloseFlag {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptSelfCloseFlag_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptSelfCloseFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionSelfCloseLocalID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptionSelfCloseLocalID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptionSelfCloseLocalID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string ParticipantID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ParticipantID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ParticipantID_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ClientID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ClientID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve2 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_reserve2_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_reserve2_get(swigCPtr);
      return ret;
    } 
  }

  public string TraderID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_TraderID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_TraderID_get(swigCPtr);
      return ret;
    } 
  }

  public int InstallID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InstallID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InstallID_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSubmitStatus {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OrderSubmitStatus_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OrderSubmitStatus_get(swigCPtr);
      return ret;
    } 
  }

  public int NotifySequence {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_NotifySequence_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_NotifySequence_get(swigCPtr);
      return ret;
    } 
  }

  public string TradingDay {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_TradingDay_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_TradingDay_get(swigCPtr);
      return ret;
    } 
  }

  public int SettlementID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_SettlementID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_SettlementID_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionSelfCloseSysID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptionSelfCloseSysID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_OptionSelfCloseSysID_get(swigCPtr);
      return ret;
    } 
  }

  public string InsertDate {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InsertDate_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InsertDate_get(swigCPtr);
      return ret;
    } 
  }

  public string InsertTime {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InsertTime_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public string CancelTime {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_CancelTime_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_CancelTime_get(swigCPtr);
      return ret;
    } 
  }

  public char ExecResult {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ExecResult_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ExecResult_get(swigCPtr);
      return ret;
    } 
  }

  public string ClearingPartID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ClearingPartID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ClearingPartID_get(swigCPtr);
      return ret;
    } 
  }

  public int SequenceNo {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_SequenceNo_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_SequenceNo_get(swigCPtr);
      return ret;
    } 
  }

  public int FrontID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_FrontID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_FrontID_get(swigCPtr);
      return ret;
    } 
  }

  public int SessionID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_SessionID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_SessionID_get(swigCPtr);
      return ret;
    } 
  }

  public string UserProductInfo {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_UserProductInfo_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_UserProductInfo_get(swigCPtr);
      return ret;
    } 
  }

  public string StatusMsg {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_StatusMsg_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_StatusMsg_get(swigCPtr);
      return ret;
    } 
  }

  public string ActiveUserID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ActiveUserID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ActiveUserID_get(swigCPtr);
      return ret;
    } 
  }

  public int BrokerOptionSelfCloseSeq {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BrokerOptionSelfCloseSeq_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BrokerOptionSelfCloseSeq_get(swigCPtr);
      return ret;
    } 
  }

  public string BranchID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BranchID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_BranchID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestUnitID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InvestUnitID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InvestUnitID_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_AccountID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_AccountID_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_CurrencyID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_CurrencyID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve3 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_reserve3_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_reserve3_get(swigCPtr);
      return ret;
    } 
  }

  public string MacAddress {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_MacAddress_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_MacAddress_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeInstID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ExchangeInstID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_ExchangeInstID_get(swigCPtr);
      return ret;
    } 
  }

  public string IPAddress {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_IPAddress_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcOptionSelfCloseField_IPAddress_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcOptionSelfCloseField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcOptionSelfCloseField(), true) {
  }

}
