//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcMarketDataBestPriceField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcMarketDataBestPriceField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcMarketDataBestPriceField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcMarketDataBestPriceField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcMarketDataBestPriceField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public double BidPrice1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_BidPrice1_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_BidPrice1_get(swigCPtr);
      return ret;
    } 
  }

  public int BidVolume1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_BidVolume1_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_BidVolume1_get(swigCPtr);
      return ret;
    } 
  }

  public double AskPrice1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_AskPrice1_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_AskPrice1_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_AskVolume1_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcMarketDataBestPriceField_AskVolume1_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcMarketDataBestPriceField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcMarketDataBestPriceField(), true) {
  }

}
