//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcTransferBankToFutureReqField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcTransferBankToFutureReqField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcTransferBankToFutureReqField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcTransferBankToFutureReqField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcTransferBankToFutureReqField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string FutureAccount {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccount_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccount_get(swigCPtr);
      return ret;
    } 
  }

  public char FuturePwdFlag {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_FuturePwdFlag_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_FuturePwdFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string FutureAccPwd {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccPwd_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccPwd_get(swigCPtr);
      return ret;
    } 
  }

  public double TradeAmt {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_TradeAmt_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_TradeAmt_get(swigCPtr);
      return ret;
    } 
  }

  public double CustFee {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_CustFee_set(swigCPtr, value);
    } 
    get {
      double ret = ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_CustFee_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyCode {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_CurrencyCode_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcTransferBankToFutureReqField_CurrencyCode_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcTransferBankToFutureReqField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcTransferBankToFutureReqField(), true) {
  }

}
