//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CThostFtdcForQuoteField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcForQuoteField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcForQuoteField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CThostFtdcForQuoteField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ctpthostmdapiPINVOKE.delete_CThostFtdcForQuoteField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string BrokerID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve1 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_reserve1_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_reserve1_get(swigCPtr);
      return ret;
    } 
  }

  public string ForQuoteRef {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ForQuoteRef_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ForQuoteRef_get(swigCPtr);
      return ret;
    } 
  }

  public string UserID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_UserID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_UserID_get(swigCPtr);
      return ret;
    } 
  }

  public string ForQuoteLocalID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ForQuoteLocalID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ForQuoteLocalID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string ParticipantID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ParticipantID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ParticipantID_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ClientID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ClientID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve2 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_reserve2_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_reserve2_get(swigCPtr);
      return ret;
    } 
  }

  public string TraderID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_TraderID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_TraderID_get(swigCPtr);
      return ret;
    } 
  }

  public int InstallID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InstallID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InstallID_get(swigCPtr);
      return ret;
    } 
  }

  public string InsertDate {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InsertDate_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InsertDate_get(swigCPtr);
      return ret;
    } 
  }

  public string InsertTime {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InsertTime_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public char ForQuoteStatus {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ForQuoteStatus_set(swigCPtr, value);
    } 
    get {
      char ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ForQuoteStatus_get(swigCPtr);
      return ret;
    } 
  }

  public int FrontID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_FrontID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_FrontID_get(swigCPtr);
      return ret;
    } 
  }

  public int SessionID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_SessionID_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_SessionID_get(swigCPtr);
      return ret;
    } 
  }

  public string StatusMsg {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_StatusMsg_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_StatusMsg_get(swigCPtr);
      return ret;
    } 
  }

  public string ActiveUserID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ActiveUserID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ActiveUserID_get(swigCPtr);
      return ret;
    } 
  }

  public int BrokerForQutoSeq {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_BrokerForQutoSeq_set(swigCPtr, value);
    } 
    get {
      int ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_BrokerForQutoSeq_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestUnitID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InvestUnitID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InvestUnitID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve3 {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_reserve3_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_reserve3_get(swigCPtr);
      return ret;
    } 
  }

  public string MacAddress {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_MacAddress_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_MacAddress_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeInstID {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ExchangeInstID_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_ExchangeInstID_get(swigCPtr);
      return ret;
    } 
  }

  public string IPAddress {
    set {
      ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_IPAddress_set(swigCPtr, value);
    } 
    get {
      string ret = ctpthostmdapiPINVOKE.CThostFtdcForQuoteField_IPAddress_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcForQuoteField() : this(ctpthostmdapiPINVOKE.new_CThostFtdcForQuoteField(), true) {
  }

}
